services:
    skywox.form.flow.create_vehicle:
        class: Skywox\AppBundle\Form\CreateVehicleFlow
        parent: craue.form.flow
        scope: request

    skywox.compliance:
        class: Skywox\AppBundle\Compliance