# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    skyflow.form.create_order:
        class: SkyFlow\AppBundle\Form\CreateOrderForm
        tags:
            - { name: form.type, alias: createVehicle }

    skyflow.form.flow.create_order:
        class: SkyFlow\AppBundle\Form\CreateOrderFlow
        parent: craue.form.flow
        scope: request
        calls:
            - [ setFormType, [ "@skyflow.form.create_order" ] ]

    skyflow.form.confirm_order:
        class: SkyFlow\AppBundle\Form\ConfirmOrderForm
        tags:
            - { name: form.type, alias: createVehicle }

    skyflow.form.flow.confirm_order:
        class: SkyFlow\AppBundle\Form\ConfirmOrderFlow
        parent: craue.form.flow
        scope: request
        calls:
            - [ setFormType, [ "@skyflow.form.confirm_order" ] ]

    skyflow.compliance:
        class: SkyFlow\AppBundle\Compliance

    app.admin.airport:
        class: SkyFlow\AppBundle\Admin\AirportAdmin
        tags:
         - { name: sonata.admin, manager_type: orm, group: General settings, label: Airports, label_catalogue: GeneralSettings }
        arguments: [null, SkyFlow\AppBundle\Entity\Airport, SkyFlowAppBundle:AirportAdmin]

    app.admin.customer:
        class: SkyFlow\AppBundle\Admin\CustomerAdmin
        tags:
         - { name: sonata.admin, manager_type: orm, group: Handling, label: Customers, label_catalogue: GeneralSettings }
        arguments: [null, SkyFlow\AppBundle\Entity\Customer, SkyFlowAppBundle:CustomerAdmin]

    app.admin.shipment:
        class: SkyFlow\AppBundle\Admin\DeliveryOrderAdmin
        tags:
         - { name: sonata.admin, manager_type: orm, group: Handling, label: Shipments, label_catalogue: GeneralSettings }
        arguments: [null, SkyFlow\AppBundle\Entity\DeliveryOrder, SkyFlowAppBundle:DeliveryOrderAdmin]

#    app.admin.processing_china:
#        class: Skywox\AppBundle\Admin\CustomerAdmin
#        tags:
#         - { name: sonata.admin, manager_type: orm, group: Handling, label: Processing China, label_catalogue: GeneralSettings }
#        arguments: [null, Skywox\AppBundle\Entity\DeliveryOrder, SkywoxAppBundle:OrderAdmin]
#
#    app.admin.processing_germany:
#        class: Skywox\AppBundle\Admin\CustomerAdmin
#        tags:
#         - { name: sonata.admin, manager_type: orm, group: Handling, label: Processing Germany, label_catalogue: GeneralSettings }
#        arguments: [null, Skywox\AppBundle\Entity\DeliveryOrder, SkywoxAppBundle:OrderAdmin]