# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    skywox.form.create_vehicle:
        class: Skywox\AppBundle\Form\CreateVehicleForm
        tags:
            - { name: form.type, alias: createVehicle }

    skywox.form.flow.create_vehicle:
        class: Skywox\AppBundle\Form\CreateVehicleFlow
        parent: craue.form.flow
        scope: request
        calls:
            - [ setFormType, [ "@skywox.form.create_vehicle" ] ]
