Skywox\GermanyCustomsBundle\Entity\N15000:
    type: entity
    table: gc_N15000
    description: Kontingentsart
    fields:
        ATP_Beschreibung_der_Überwachungsart:
            type: string
            length: 200
            otype: VARCHAR
    id:
        ATO_Schlüssel_der_Überwachungsart:
            type: string
            length: 2
            otype: CHAR
