Skywox\GermanyCustomsBundle\Entity\N20005:
    type: entity
    table: gc_N20005
    description: 'Zuordnung Abgabenart zur "sekundären" Maßnahmeart'
    fields:
        AUH_Endedatum:
            type: edidatetime
            otype: DATE
    id:
        AUE_Abgabenart_der_zZt_in_Prüfung_befindlichen_Maßnahme:
            type: string
            length: 2
            otype: CHAR
        AUF_Maßnahmeart_der_zusätzlich_auszuwertenden_Maßnahme:
            type: string
            length: 6
            otype: CHAR
        AUG_Beginndatum:
            type: edidatetime
            otype: DATE
