Skywox\GermanyCustomsBundle\Entity\N20000:
    type: entity
    table: gc_N20000
    description: Abgabenart
    fields:
        ATZ_Endedatum:
            type: edidatetime
            otype: DATE
        AUA_Abkürzung_der_Maßnahmeart:
            type: integer
            length: 1
            otype: NUMBER
        AUC_Beschreibung_der_Abgabenart:
            type: string
            length: 500
            otype: VARCHAR
        AUD_Kurzform_der_Abgabenart:
            type: string
            length: 500
            otype: VARCHAR
    id:
        ATW_Abgabenart:
            type: string
            length: 2
            otype: CHAR
        ATX_Herkunft_der_Abgabenart:
            type: string
            length: 1
            otype: CHAR
        ATY_Beginndatum:
            type: edidatetime
            otype: DATE
