Skywox\GermanyCustomsBundle\Entity\N20300:
    type: entity
    table: gc_N20300
    description: Abk체rzungen
    fields:
        AUJ_Erl채uternder_Text_zur_Abk체rzung:
            type: string
            length: 200
            otype: VARCHAR
    id:
        AUI_Abk체rzung:
            type: string
            length: 50
            otype: VARCHAR
