Skywox\GermanyCustomsBundle\Entity\N21500:
    type: entity
    table: gc_N21500
    description: Maßnahmeaktion
    fields:
        AVD_Endedatum:
            type: edidatetime
            otype: DATE
        AVE_Beschreibung_der_Maßnahmeaktion:
            type: string
            length: 500
            otype: VARCHAR
    id:
        AVB_Maßnahmeaktion:
            type: string
            length: 3
            otype: CHAR
        AVC_Beginndatum:
            type: edidatetime
            otype: DATE
