Skywox\GermanyCustomsBundle\Entity\N24010:
    type: entity
    table: gc_N24010
    description: Bescheinigungsartcodierung
    fields:
        AWK_Endedatum:
            type: edidatetime
            otype: DATE
    id:
        AWH_Bescheinigungsart:
            type: string
            length: 1
            otype: CHAR
        AWI_Schlüssel_der_Bescheinigung:
            type: string
            length: 3
            otype: VARCHAR
        AWJ_Beginndatum:
            type: edidatetime
            otype: DATE
