Skywox\GermanyCustomsBundle\Entity\N28500:
    type: entity
    table: gc_N28500
    description: Maßeinheiten
    fields:
        AZE_Endedatum:
            type: edidatetime
            otype: DATE
        AZF_Bezeichnung_der_Maßeinheit_entsprechend_der_Darstellung_im_:
            type: string
            length: 500
            otype: VARCHAR
        AZG_Beschreibung_der_Maßeinheit:
            type: string
            length: 500
            otype: VARCHAR
    id:
        AZB_Schlüssel_der_Maßeinheit:
            type: string
            length: 3
            otype: CHAR
        AZC_Herkunft_der_Maßeinheit_TARIC_national:
            type: string
            length: 1
            otype: CHAR
        AZD_Beginndatum:
            type: edidatetime
            otype: DATE
