Skywox\GermanyCustomsBundle\Entity\N29500:
    type: entity
    table: gc_N29500
    description: Mittelwert
    fields:
        AZR_Endedatum_des_Mittelwerts:
            type: edidatetime
            otype: DATE
        AZS_EX_Präfix_Mittelwert:
            type: string
            length: 2
            otype: CHAR
        AZT_Betrag:
            type: decimal
            precision: 10
            scale: 3
            otype: NUMBER
        AZU_Maßeinheit:
            type: string
            length: 3
            otype: CHAR
        AZV_Maßeinheitsqualifikator:
            type: string
            length: 1
            otype: CHAR
    id:
        AZN_Warennomenklatur_ID:
            type: string
            length: 10
            otype: CHAR
        AZO_Warenliniensuffix:
            type: string
            length: 2
            otype: CHAR
        AZP_Beginndatum_der_Warennomenklatur_ID:
            type: edidatetime
            otype: DATE
        AZQ_Beginndatum_des_Mittelwerts:
            type: edidatetime
            otype: DATE
