Skywox\GermanyCustomsBundle\Entity\N30500:
    type: entity
    table: gc_N30500
    description: Stichworte
    fields:
        BAO_Stichwort:
            type: string
            length: 255
            otype: VARCHAR
        BAP_Fundstelle:
            type: string
            length: 50
            otype: VARCHAR
        BAR_Endedatum:
            type: edidatetime
            otype: DATE
        BAS_Teil_der_Erläuterungen:
            type: string
            length: 3
            otype: VARCHAR
    id:
        BAN_SID_für_Stichwort:
            type: integer
            length: 8
            otype: NUMBER
        BAQ_Beginndatum:
            type: edidatetime
            otype: DATE
