Skywox\GermanyCustomsBundle\Entity\N30700:
    type: entity
    table: gc_N30700
    description: 'Zuordnung Verbrauchsteuerarten– Kreditierungsarten'
    fields:
        BAW_Endedatum:
            type: edidatetime
            otype: DATE
    id:
        BAT_Verbrauchsteuerart_ID:
            type: string
            length: 2
            otype: CHAR
        BAU_Kreditierungsart_ID:
            type: string
            length: 1
            otype: CHAR
        BAV_Beginndatum:
            type: edidatetime
            otype: DATE
