Skywox\GermanyCustomsBundle\Entity\N31000:
    type: entity
    table: gc_N31000
    description: 'Zuordnung Warenverkehrsbescheinigung – geographisches Gebiet'
    fields:
        BBB_Endedatum:
            type: edidatetime
            otype: DATE
    id:
        BAX_Bescheinigungsart:
            type: string
            length: 1
            otype: CHAR
        BAY_Bescheinigung:
            type: string
            length: 3
            otype: VARCHAR
        BAZ_Geographisches_Gebiet:
            type: string
            length: 4
            otype: CHAR
        BBA_Beginndatum:
            type: edidatetime
            otype: DATE
