Skywox\GermanyCustomsBundle\Entity\N35000:
    type: entity
    table: gc_N35000
    description: 'Zuordnung AHStat- Schlüssel – Bundesland'
    fields:
        BBE_Endedatum:
            type: edidatetime
            otype: DATE
        BBF_Name_des_Bundeslandes:
            type: string
            length: 200
            otype: VARCHAR
        BBG_Kurzbezeichnung_im_Länderverzeichnis_der_Außenhandelsstati:
            type: string
            length: 50
            otype: VARCHAR
    id:
        BBC_AHStat_Verschlüsselung_des_Bundeslandes:
            type: string
            length: 2
            otype: CHAR
        BBD_Beginndatum:
            type: edidatetime
            otype: DATE
