SkyFlow\GermanyCustomsBundle\Entity\N36000:
    type: entity
    table: gc_N36000
    description: Abgabengruppe
    fields:
        BBJ_Endedatum:
            type: edidatetime
            otype: DATE
        BBK_Bezeichnung_der_Abgabengruppe:
            type: string
            length: 200
            otype: VARCHAR
    id:
        BBH_Schlüssel_der_Abgabengruppe:
            type: string
            length: 2
            otype: CHAR
        BBI_Beginndatum:
            type: edidatetime
            otype: DATE
