Skywox\GermanyCustomsBundle\Entity\N40005:
    type: entity
    table: gc_N40005
    description: 'nationale Maßnahmebedingungskomponenten'
    fields:
        BCS_SID_der_nationalen_Maßnahme:
            type: integer
            length: 8
            otype: NUMBER
        BCT_Bedingung:
            type: string
            length: 2
            otype: CHAR
        BCU_Sequentielle_Nummer_der_Bedingung:
            type: string
            length: 3
            otype: CHAR
        BCV_Abgabenbetrag_der_Bedingung:
            type: decimal
            precision: 10
            scale: 3
            otype: NUMBER
        BCW_Währungseinheit_der_Bedingung:
            type: string
            length: 3
            otype: CHAR
        BCX_Maßeinheit_der_Bedingung:
            type: string
            length: 3
            otype: CHAR
        BCY_Maßeinheitsqualifikator_der_Bedingung:
            type: string
            length: 1
            otype: CHAR
        BCZ_Maßnahmeaktion:
            type: string
            length: 3
            otype: CHAR
        BDA_Bescheinigungsart:
            type: string
            length: 1
            otype: CHAR
        BDB_Schlüssel_der_Bescheinigung:
            type: string
            length: 3
            otype: VARCHAR
    id:
        BCR_SID_der_Bedingungskomponente:
            type: integer
            length: 8
            otype: NUMBER
