Skywox\GermanyCustomsBundle\Entity\N41005:
    type: entity
    table: gc_N41005
    description: 'Zuordnung Verbrauchsteuern – Fußnoten'
    fields:
        BEH_Endedatum:
            type: edidatetime
            otype: DATE
    id:
        BED_SID_der_Verbrauchsteuer:
            type: integer
            length: 8
            otype: NUMBER
        BEE_Fußnotenart_ID:
            type: string
            length: 3
            otype: CHAR
        BEF_Fußnote:
            type: string
            length: 5
            otype: CHAR
        BEG_Beginndatum:
            type: edidatetime
            otype: DATE
