Skywox\GermanyCustomsBundle\Entity\N50000:
    type: entity
    table: gc_N50000
    description: 'Ausfuhrerstattungsnomenklatur (AE-Nomenklatur)'
    fields:
        BGH_Beginndatum:
            type: edidatetime
            otype: DATE
        BGI_Endedatum:
            type: edidatetime
            otype: DATE
        BGJ_Warennomenklaturlinie:
            type: string
            length: 10
            otype: CHAR
        BGK_Zusatzcodeart:
            type: string
            length: 1
            otype: CHAR
        BGL_Zusatzcode:
            type: string
            length: 3
            otype: CHAR
        BGM_Warenliniensuffix:
            type: string
            length: 2
            otype: CHAR
        BGN_SID_der_Warennomenklaturlinie:
            type: integer
            length: 8
            otype: NUMBER
        BGO_Anzahl_der_Führungsstriche:
            type: string
            length: 2
            otype: CHAR
        BGP_Ergänzende_Warenbeschreibung:
            type: string
            length: 2000
            otype: VARCHAR
    id:
        BGG_SID_für_die_nationale_AE_Nomenklatur:
            type: integer
            length: 8
            otype: NUMBER
