Skywox\GermanyCustomsBundle\Entity\N50100:
    type: entity
    table: gc_N50100
    description: 'Zuordnung Ausfuhrerstattungsnomenklatur – Fußnoten'
    fields:
        BGS_Endedatum:
            type: edidatetime
            otype: DATE
    id:
        BGQ_SID_für_die_AE_Nomenklatur:
            type: integer
            length: 8
            otype: NUMBER
        BGR_Beginndatum:
            type: edidatetime
            otype: DATE
        BGT_Fußnotenart_ID:
            type: string
            length: 3
            otype: CHAR
        BGU_Fußnote:
            type: string
            length: 5
            otype: CHAR
