Skywox\GermanyCustomsBundle\Entity\N50200:
    type: entity
    table: gc_N50200
    description: 'Zuordnung Ausfuhrerstattungsnomenklatur – Fußnoten'
    fields:
        BGX_Endedatum:
            type: edidatetime
            otype: DATE
    id:
        BGV_SID_der_nationalen_AE_Nomenklatur:
            type: integer
            length: 8
            otype: NUMBER
        BGW_Beginndatum:
            type: edidatetime
            otype: DATE
        BGY_Fußnotenart_ID:
            type: string
            length: 3
            otype: CHAR
        BGZ_Fußnote:
            type: string
            length: 5
            otype: CHAR
