Skywox\GermanyCustomsBundle\Entity\N61000:
    type: entity
    table: gc_N61000
    description: 'Güter mit doppeltem Verwendungszweck (Dual- Use –VO)'
    fields:
        BHM_Endedatum:
            type: edidatetime
            otype: DATE
        BHN_Langbeschreibung:
            type: text
            otype: CLOB
        BHO_zusätzliche_Informationen:
            type: text
            otype: CLOB
    id:
        BHK_Beschränkungsgrund:
            type: string
            length: 10
            otype: CHAR
        BHL_Beginndatum:
            type: edidatetime
            otype: DATE
