Skywox\GermanyCustomsBundle\Entity\N61010:
    type: entity
    table: gc_N61010
    description: 'Verweise auf weitere Beschr채nkungen bei G체tern mit doppeltem Verwendungszweck'
    fields:
        BHW_Endedatum:
            type: edidatetime
            otype: DATE
    id:
        BHT_Beschr채nkungsgrund:
            type: string
            length: 10
            otype: CHAR
        BHU_Verweis_auf_weitere_Beschr채nkungen:
            type: string
            length: 10
            otype: CHAR
        BHV_Beginndatum:
            type: edidatetime
            otype: DATE
