Skywox\GermanyCustomsBundle\Entity\N61200:
    type: entity
    table: gc_N61200
    description: 'Ausfuhrliste Teil 1'
    fields:
        BIG_Endedatum:
            type: edidatetime
            otype: DATE
        BIH_Beschreibung:
            type: text
            otype: CLOB
        BII_Anmerkung:
            type: text
            otype: CLOB
    id:
        BIE_Ausfuhrlistennummer:
            type: string
            length: 10
            otype: CHAR
        BIF_Beginndatum:
            type: edidatetime
            otype: DATE
