Skywox\GermanyCustomsBundle\Entity\T10000:
    type: entity
    table: gc_T10000
    description: Fußnotenart-ID
    fields:
        AAD_Beginndatum:
            type: edidatetime
            otype: DATE
        AAE_Endedatum:
            type: edidatetime
            otype: DATE
        AAF_Anwendungscode_der_Fußnotenart_ID:
            type: string
            length: 1
            otype: CHAR
        AAG_Beschreibung_der_Fußnotenart_ID:
            type: string
            length: 500
            otype: VARCHAR
    id:
        AAC_Fußnotenart_ID:
            type: string
            length: 3
            otype: CHAR
