Skywox\GermanyCustomsBundle\Entity\T11000:
    type: entity
    table: gc_T11000
    description: Bescheinigungsart
    fields:
        AAI_Beginndatum:
            type: edidatetime
            otype: DATE
        AAJ_Endedatum:
            type: edidatetime
            otype: DATE
        AAK_Beschreibung_der_Bescheinigungsart:
            type: string
            length: 500
            otype: VARCHAR
    id:
        AAH_Code_der_Bescheinigungsart:
            type: string
            length: 1
            otype: CHAR
