SkyFlow\GermanyCustomsBundle\Entity\T20005:
    type: entity
    table: gc_T20005
    description: Fußnotenzeitraumbeschreibung
    fields:
        ABV_Fußnotenart_ID:
            type: string
            length: 3
            otype: CHAR
        ABW_Fußnoten_ID:
            type: string
            length: 5
            otype: CHAR
        ABX_Datum_des_Gültigkeitsbeginns_der_Fußnotenbeschreibung:
            type: edidatetime
            otype: DATE
        ABY_Gültigkeitsendedatum_der_Fußnotenbeschreibung:
            type: edidatetime
            otype: DATE
        ABZ_Beschreibung_der_Fußnote:
            type: text
            otype: LONG
    id:
        ABU_SID_der_Fußnotenbeschreibung:
            type: integer
            length: 8
            otype: NUMBER
