Skywox\GermanyCustomsBundle\Entity\T21000:
    type: entity
    table: gc_T21000
    description: Maßeinheit
    fields:
        ACL_Datum_des_Gültigkeitsbeginns_des_Maßeinheitscodes:
            type: edidatetime
            otype: DATE
        ACM_Gültigkeitsendedatum_des_Maßeinheitscodes:
            type: edidatetime
            otype: DATE
        ACN_Beschreibung_der_Maßeinheit:
            type: string
            length: 500
            otype: VARCHAR
    id:
        ACK_Maßeinheitscode:
            type: string
            length: 3
            otype: CHAR
