Skywox\GermanyCustomsBundle\Entity\T21500:
    type: entity
    table: gc_T21500
    description: Maßeinheitsqualifikator
    fields:
        ACP_Datum_des_Gültigkeitsbeginns_des_Codes_des_Maßeinheitsqual:
            type: edidatetime
            otype: DATE
        ACQ_Gültigkeitsendedatum_des_Codes_des_Maßeinheitsqualifikator:
            type: edidatetime
            otype: DATE
        ACR_Beschreibung_des_Maßeinheitsqualifikators:
            type: string
            length: 500
            otype: VARCHAR
    id:
        ACO_Code:
            type: string
            length: 1
            otype: CHAR
