SkyFlow\GermanyCustomsBundle\Entity\T22500:
    type: entity
    table: gc_T22500
    description: Währungseinheit
    fields:
        ACX_Datum_des_Gültigkeitsbeginns_des_Codes_der_Währungseinheit:
            type: edidatetime
            otype: DATE
        ACY_Gültigkeitsendedatum_des_Codes_der_Währungseinheit:
            type: edidatetime
            otype: DATE
        ACZ_Beschreibung_der_Währungseinheit:
            type: string
            length: 500
            otype: VARCHAR
    id:
        ACW_Code_der_Währungseinheit:
            type: string
            length: 3
            otype: CHAR
