Skywox\GermanyCustomsBundle\Entity\T23500:
    type: entity
    table: gc_T23500
    description: Maßnahmeart
    fields:
        ADI_Datum_des_Gültigkeitsbeginns_der_Maßnahmeart_ID:
            type: edidatetime
            otype: DATE
        ADJ_Gültigkeitsendedatum_der_Maßnahmeart_ID:
            type: edidatetime
            otype: DATE
        ADK_Handelsbewegungscode:
            type: string
            length: 1
            otype: CHAR
        ADL_Prioritätscode:
            type: string
            length: 1
            otype: CHAR
        ADM_Anwendbarer_Code_der_Maßnahmekomponente:
            type: string
            length: 1
            otype: CHAR
        ADN_Ursprungs__Bestimmungscode:
            type: string
            length: 1
            otype: CHAR
        ADO_Ordnungsnummererfassungscode:
            type: string
            length: 1
            otype: CHAR
        ADP_Hierarchische_Maßnahmeebene:
            type: string
            length: 2
            otype: CHAR
        ADQ_Maßnahmeartserien_ID:
            type: string
            length: 2
            otype: CHAR
        ADR_Beschreibung_der_Maßnahmeart:
            type: string
            length: 500
            otype: VARCHAR
    id:
        ADH_Maßnahmeart_ID:
            type: string
            length: 6
            otype: CHAR
