Skywox\GermanyCustomsBundle\Entity\T24500:
    type: entity
    table: gc_T24500
    description: Zusatzcode
    fields:
        ADX_Zusatzcodeart_ID:
            type: string
            length: 1
            otype: CHAR
        ADY_Zusatzcode:
            type: string
            length: 3
            otype: CHAR
        ADZ_Datum_des_Gültigkeitsbeginns_des_Zusatzcodes:
            type: edidatetime
            otype: DATE
        AEA_Gültigkeitsendedatum_des_Zusatzcodes:
            type: edidatetime
            otype: DATE
    id:
        ADW_SID_des_Zusatzcodes:
            type: integer
            length: 8
            otype: NUMBER
