Skywox\GermanyCustomsBundle\Entity\T24505:
    type: entity
    table: gc_T24505
    description: 'Zeitraum der Zusatzcodebeschreibung'
    fields:
        AEC_SID_des_Zusatzcodes:
            type: integer
            length: 8
            otype: NUMBER
        AED_Zusatzcodeart_ID:
            type: string
            length: 1
            otype: CHAR
        AEE_Zusatzcode:
            type: string
            length: 3
            otype: CHAR
        AEF_Datum_des_Gültigkeitsbeginns_der_Zusatzcodebeschreibung:
            type: edidatetime
            otype: DATE
        AEG_Datum_des_Gültigkeitsende_der_Zusatzcodebeschreibung:
            type: edidatetime
            otype: DATE
        AEH_Beschreibung_des_Zusatzcodes:
            type: text
            otype: LONG
    id:
        AEB_SID_der_Zusatzcodebeschreibung:
            type: integer
            length: 8
            otype: NUMBER
