Skywox\GermanyCustomsBundle\Entity\T27000:
    type: entity
    table: gc_T27000
    description: Warennomenklaturgruppe
    fields:
        AFH_Datum_des_Gültigkeitsbeginns_der_Warennomenklaturgruppe:
            type: edidatetime
            otype: DATE
        AFI_Gültigkeitsendedatum_der_Warennomenklaturgruppe:
            type: edidatetime
            otype: DATE
        AFJ_Mögliche_Codes_der_Nomenklaturgruppe:
            type: string
            length: 1
            otype: CHAR
        AFK_Beschreibung_der_Nomenklaturgruppe:
            type: string
            length: 500
            otype: VARCHAR
    id:
        AFF_Art_der_Warennomenklaturgruppe:
            type: string
            length: 1
            otype: CHAR
        AFG_Warennomenklaturgruppen_ID:
            type: string
            length: 6
            otype: CHAR
