SkyFlow\GermanyCustomsBundle\Entity\T28500:
    type: entity
    table: gc_T28500
    description: Basisverordnung
    fields:
        AGE_Veröffentlichungsdatum_der_Basisverordnung:
            type: edidatetime
            otype: DATE
        AGF_Nummer_des_Amtsblattes:
            type: string
            length: 5
            otype: CHAR
        AGG_Amtsblatt_Seite:
            type: string
            length: 4
            otype: CHAR
        AGH_Datum_des_Gültigkeitsbeginns_der_Basisverordnung:
            type: edidatetime
            otype: DATE
        AGI_Gültigkeitsendedatum_der_Basisverordnung:
            type: edidatetime
            otype: DATE
        AGJ_tatsächliches_Endedatum_der_Basisverordnung:
            type: edidatetime
            otype: DATE
        AGK_Gemeinschaftscode:
            type: string
            length: 1
            otype: CHAR
        AGL_Verordnungsgruppen_ID:
            type: string
            length: 3
            otype: CHAR
        AGM_Funktion_der_Antidumpingverordnung:
            type: string
            length: 1
            otype: CHAR
        AGN_Verwandter_Antidumpingverordnungs_ID:
            type: string
            length: 8
            otype: CHAR
        AGO_Funktion_der_vollständigen_Aufhebungsverordnung:
            type: string
            length: 1
            otype: CHAR
        AGP_ID_der_vollständigen_Aufhebungsverordnung:
            type: string
            length: 8
            otype: CHAR
        AGQ_Funktion_der_expliziten_Aufhebungsverordnung:
            type: string
            length: 1
            otype: CHAR
        AGR_ID_der_expliziten_Aufhebungsverordnung:
            type: string
            length: 8
            otype: CHAR
        AGS_Ersatzindikator:
            type: string
            length: 1
            otype: CHAR
        AGT_ausgesetztes_Merkmal:
            type: string
            length: 1
            otype: CHAR
        AGU_Informationstext:
            type: string
            length: 500
            otype: VARCHAR
        AGV_Billigungsindikator:
            type: string
            length: 1
            otype: CHAR
    id:
        AGC_Basisverordnungsfunktion:
            type: string
            length: 1
            otype: CHAR
        AGD_Basisverordnungs_ID:
            type: string
            length: 8
            otype: CHAR
