SkyFlow\GermanyCustomsBundle\Entity\T30500:
    type: entity
    table: gc_T30500
    description: 'Ersatz einer Entwurfsverordnung durch eine "echte" Verordnung (Verordnungsersatz)'
    fields: {  }
    id:
        AIU_Funktion_des_Ersatzes_der_Verordnung:
            type: string
            length: 1
            otype: CHAR
        AIV_ID_des_Ersatzes_der_Verordnung:
            type: string
            length: 8
            otype: CHAR
        AIW_Ersetzte_Verordnungsfunktion:
            type: string
            length: 1
            otype: CHAR
        AIX_Ersetzter_Verordnungs_ID:
            type: string
            length: 8
            otype: CHAR
        AIY_Maßnahmeart_ID:
            type: string
            length: 6
            otype: CHAR
        AIZ_ID_des_geographischen_Gebiets:
            type: string
            length: 4
            otype: CHAR
        AJA_Kapitelnummer:
            type: string
            length: 2
            otype: CHAR
