Skywox\GermanyCustomsBundle\Entity\T32500:
    type: entity
    table: gc_T32500
    description: Meursing-Position
    fields:
        AJH_Datum_des_Gültigkeitsbeginns_der_Meursing_Position:
            type: edidatetime
            otype: DATE
        AJI_Gültigkeitsendedatum_der_Meursing__Position:
            type: edidatetime
            otype: DATE
        AJJ_Beschreibung_der_Meursing_Position:
            type: string
            length: 500
            otype: VARCHAR
    id:
        AJE_ID_des_Meursing_Tabellenplans:
            type: string
            length: 2
            otype: CHAR
        AJF_Meursing_Positionsnummer:
            type: string
            length: 3
            otype: CHAR
        AJG_Meursing_Reihen__Spaltencode:
            type: string
            length: 1
            otype: CHAR
