SkyFlow\GermanyCustomsBundle\Entity\T33000:
    type: entity
    table: gc_T33000
    description: Meursing-Unterposition
    fields:
        AJV_Datum_des_Gültigkeitsbeginns_der_Meursing_Unterposition:
            type: edidatetime
            otype: DATE
        AJW_Gültigkeitsendedatum_der_Meursing_Unterposition:
            type: edidatetime
            otype: DATE
        AJX_Kurztext_der_Meursing_Unterposition:
            type: string
            length: 500
            otype: VARCHAR
    id:
        AJR_ID_des_Meursing_Tabellenplans:
            type: string
            length: 2
            otype: CHAR
        AJS_Meursing_Positionsnummer:
            type: string
            length: 3
            otype: CHAR
        AJT_Meursing_Reihen__Spaltencode:
            type: string
            length: 1
            otype: CHAR
        AJU_Sequentielle_Nummer_der_Meursing_Unterposition:
            type: string
            length: 4
            otype: CHAR
