Skywox\GermanyCustomsBundle\Entity\T34000:
    type: entity
    table: gc_T34000
    description: 'Zusatzcode Meursing'
    fields:
        AJZ_Gültigkeitsendedatum_des_Zusatzcode_Meursing:
            type: edidatetime
            otype: DATE
        AKA_Zusatzcode_Meursing:
            type: string
            length: 3
            otype: CHAR
        AKB_Datum_des_Gültigkeitsbeginns_des_Zusatzcode_Meursing:
            type: edidatetime
            otype: DATE
    id:
        AJY_SID_für_Zusatzcode_Meursing:
            type: integer
            length: 8
            otype: NUMBER
