Skywox\GermanyCustomsBundle\Entity\T36000:
    type: entity
    table: gc_T36000
    description: 'Ordnungsnummer QUOTA'
    fields:
        AKT_Ordnungsnummer:
            type: string
            length: 6
            otype: CHAR
        AKU_Gültigkeitsbeginn:
            type: edidatetime
            otype: DATE
        AKV_Gültigkeitsende:
            type: edidatetime
            otype: DATE
    id:
        AKS_SID_der_Ordnungsnummer:
            type: integer
            length: 8
            otype: NUMBER
