Skywox\GermanyCustomsBundle\Entity\T37005:
    type: entity
    table: gc_T37005
    description: 'Gegenseitiger Bezug von Kontingenten'
    fields:
        ALU_Typ_des_verwandten_Unterkontingents:
            type: string
            length: 2
            otype: CHAR
        ALV_Koeffizient:
            type: decimal
            precision: 16
            scale: 5
            otype: NUMBER
    id:
        ALS_SID_der_QUOTA_Beschreibung_Hauptkontingent:
            type: integer
            length: 8
            otype: NUMBER
        ALT_SID_der_QUOTA_Beschreibung_Unterkontingent:
            type: integer
            length: 8
            otype: NUMBER
