Skywox\GermanyCustomsBundle\Entity\T37015:
    type: entity
    table: gc_T37015
    description: 'Zeitraum der Aussetzung eines Kontingents'
    fields:
        AMD_SID_der_QUOTA_Beschreibung:
            type: integer
            length: 8
            otype: NUMBER
        AME_Beginn_der_Aussetzung:
            type: edidatetime
            otype: DATE
        AMF_Ende_der_Aussetzung:
            type: edidatetime
            otype: DATE
        AMG_Kurzbeschreibung_Grund_der_Aussetzung:
            type: string
            length: 500
            otype: VARCHAR
    id:
        AMC_SID_des_Zeitraums_der_Aussetzung:
            type: integer
            length: 8
            otype: NUMBER
