Skywox\GermanyCustomsBundle\Entity\T37505:
    type: entity
    table: gc_T37505
    description: 'Aufhebung der Sperrung eines Kontingents'
    fields:
        AMO_Datum_der_Aufhebung_der_Sperrung:
            type: edidatetime
            otype: DATE
    id:
        AMM_SID_der_QUOTA_Beschreibung:
            type: integer
            length: 8
            otype: NUMBER
        AMN_Datum_und_Uhrzeit:
            type: edidatetime
            otype: DATE
