Skywox\GermanyCustomsBundle\Entity\T37500:
    type: entity
    table: gc_T37500
    description: 'Aktuelle Kontingentsmenge'
    fields:
        AMJ_alter_Bestand:
            type: decimal
            precision: 14
            scale: 3
            otype: NUMBER
        AMK_neuer_Bestand:
            type: decimal
            precision: 14
            scale: 3
            otype: NUMBER
        AML_eingeführte_Menge:
            type: decimal
            precision: 14
            scale: 3
            otype: NUMBER
    id:
        AMH_SID_der_QUOTA_Beschreibung:
            type: integer
            length: 8
            otype: NUMBER
        AMI_Datum_und_Uhrzeit:
            type: edidatetime
            otype: DATE
