Skywox\GermanyCustomsBundle\Entity\T37530:
    type: entity
    table: gc_T37530
    description: 'Schließung eines Kontingents und Übertragung der Restmenge auf ein übergeordnetes Kontingent'
    fields:
        ANE_Datum_der_Schließung:
            type: edidatetime
            otype: DATE
        ANF_Übertragungsmenge:
            type: decimal
            precision: 14
            scale: 3
            otype: NUMBER
        ANG_SID_des_Zielkontingents:
            type: integer
            length: 8
            otype: NUMBER
    id:
        ANC_SID_der_QUOTA_Beschreibung:
            type: integer
            length: 8
            otype: NUMBER
        AND_Datum_und_Uhrzeit:
            type: edidatetime
            otype: DATE
