Skywox\GermanyCustomsBundle\Entity\T38000:
    type: entity
    table: gc_T38000
    description: Höchstmenge
    fields:
        ANJ_Gültigkeitsende:
            type: edidatetime
            otype: DATE
        ANK_Datum_des_Erreichens_der_Höchstmenge:
            type: edidatetime
            otype: DATE
    id:
        ANH_Ordnungsnummer:
            type: string
            length: 6
            otype: CHAR
        ANI_Gültigkeitsbeginn:
            type: edidatetime
            otype: DATE
