SkyFlow\GermanyCustomsBundle\Entity\T40025:
    type: entity
    table: gc_T40025
    description: 'Mitgliedschaft der Warennomenklaturlinie einer Warennomenklaturgruppe'
    fields:
        AOQ_Gültigkeitsendedatum_der_Mitgliedschaft_der_Warennomenklatu:
            type: edidatetime
            otype: DATE
        AOR_Warennomenklatur_ID:
            type: string
            length: 10
            otype: CHAR
        AOS_Warenliniensuffix:
            type: string
            length: 2
            otype: CHAR
    id:
        AOM_SID_der_Warennomenklatur:
            type: integer
            length: 8
            otype: NUMBER
        AON_Nomenklaturgruppenart:
            type: string
            length: 1
            otype: CHAR
        AOO_Warennomenklaturgruppe:
            type: string
            length: 6
            otype: CHAR
        AOP_Datum_des_Gültigkeitsbeginns_der_Mitgliedschaft_der_Warenno:
            type: edidatetime
            otype: DATE
