Skywox\GermanyCustomsBundle\Entity\T40000:
    type: entity
    table: gc_T40000
    description: Warennomenklatur
    fields:
        ANM_Warennomenklatur_ID:
            type: string
            length: 10
            otype: CHAR
        ANN_Warenliniensuffix:
            type: string
            length: 2
            otype: CHAR
        ANO_Datum_des_Gültigkeitsbeginns_der_Warennomenklatur:
            type: edidatetime
            otype: DATE
        ANP_Gültigkeitsendedatum_der_Warennomenklatur:
            type: edidatetime
            otype: DATE
        ANQ_Statistischer_nicht_statistischer_Indikator:
            type: string
            length: 1
            otype: CHAR
    id:
        ANL_SID_für_die_Warennomenklatur:
            type: integer
            length: 8
            otype: NUMBER
