SkyFlow\GermanyCustomsBundle\Entity\T40020:
    type: entity
    table: gc_T40020
    description: 'Verbindung Fußnote- Warennomenklatur'
    fields:
        AOJ_Gültigkeitsendedatum_der_Verbindung_zwischen_Fußnote_und_W:
            type: edidatetime
            otype: DATE
        AOK_Warennomenklatur_ID:
            type: string
            length: 10
            otype: CHAR
        AOL_Warenliniensuffix:
            type: string
            length: 2
            otype: CHAR
    id:
        AOF_SID_der_Warennomenklatur:
            type: integer
            length: 8
            otype: NUMBER
        AOG_Fußnotenart_ID:
            type: string
            length: 3
            otype: CHAR
        AOH_Fußnoten_ID:
            type: string
            length: 5
            otype: CHAR
        AOI_Datum_des_Gültigkeitsbeginns_der_Verbindung_zwischen_Fußno:
            type: edidatetime
            otype: DATE
