Skywox\GermanyCustomsBundle\Entity\T40005:
    type: entity
    table: gc_T40005
    description: 'Führungsstriche zur Warennomenklatur'
    fields:
        ANS_SID_für_die_Warennomenklatur:
            type: integer
            length: 8
            otype: NUMBER
        ANT_Datum_des_Gültigkeitsbeginns_der_Warennomenklaturführungss:
            type: edidatetime
            otype: DATE
        ANU_Gültigkeitsendedatum_der_Warennomenklaturführungsstriche:
            type: edidatetime
            otype: DATE
        ANV_Anzahl_der_Führungsstriche:
            type: string
            length: 2
            otype: CHAR
        ANW_Warennomenklatur_ID:
            type: string
            length: 10
            otype: CHAR
        ANX_Warenliniensuffix:
            type: string
            length: 2
            otype: CHAR
    id:
        ANR_SID_für_Warennomenklaturführungsstriche:
            type: integer
            length: 8
            otype: NUMBER
