Skywox\GermanyCustomsBundle\Entity\T41005:
    type: entity
    table: gc_T41005
    description: 'Führungsstriche zur Ausfuhrerstattungsnomenklatur'
    fields:
        APM_SID_der_Ausfuhrerstattungsnomenklatur:
            type: integer
            length: 8
            otype: NUMBER
        APN_Datum_des_Gültigkeitsbeginns_der_Ausfuhrerstattungsnomenkla:
            type: edidatetime
            otype: DATE
        APO_Gültigkeitsendedatum_der_Ausfuhrerstattungsnomenklaturführ:
            type: edidatetime
            otype: DATE
        APP_Anzahl_der_Ausfuhrerstattungsnomenklaturführungsstriche:
            type: string
            length: 2
            otype: CHAR
        APQ_Warennomenklatur_ID:
            type: string
            length: 10
            otype: CHAR
        APR_Zusatzcodeart:
            type: string
            length: 1
            otype: CHAR
        APS_Ausfuhrerstattungscode:
            type: string
            length: 3
            otype: CHAR
        APT_Warenliniensuffix:
            type: string
            length: 2
            otype: CHAR
    id:
        APL_SID_für_die_Führungsstriche_der_Ausfuhrerstattungsnomenkla:
            type: integer
            length: 8
            otype: NUMBER
