Skywox\GermanyCustomsBundle\Entity\T43011:
    type: entity
    table: gc_T43011
    description: Maßnahmebedingungsaktion
    fields:
        ASA_Abgabenbetrag:
            type: decimal
            precision: 10
            scale: 3
            otype: NUMBER
        ASB_Code_der_Währungseinheit:
            type: string
            length: 3
            otype: CHAR
        ASC_Maßeinheitscode:
            type: string
            length: 3
            otype: CHAR
        ASD_Code_des_Maßeinheitsqualifikators:
            type: string
            length: 1
            otype: CHAR
    id:
        ARY_SID_der_Maßnahmebedingung:
            type: integer
            length: 8
            otype: NUMBER
        ARZ_ID_der_Abgabenart:
            type: string
            length: 2
            otype: CHAR
