SkyFlow\GermanyCustomsBundle\Entity\T44000:
    type: entity
    table: gc_T44000
    description: Währungsumrechnungszeitraum
    fields:
        ASU_Code_der_Währungseinheit_des_Vaters:
            type: string
            length: 3
            otype: CHAR
        ASV_Anfangsdatum_vom_Umrechnungszeitraum:
            type: edidatetime
            otype: DATE
        ASW_Endedatum_vom_Umrechnungszeitraum:
            type: edidatetime
            otype: DATE
    id:
        AST_SID_für_den_Umrechnungszeitraum:
            type: integer
            length: 8
            otype: NUMBER
