Skywox\GermanyCustomsBundle\Entity\T44005:
    type: entity
    table: gc_T44005
    description: Währungsumrechnungskurs
    fields:
        ASZ_Umrechnungskurs:
            type: decimal
            precision: 16
            scale: 8
            otype: NUMBER
    id:
        ASX_SID_für_den_Umrechnungszeitraum:
            type: integer
            length: 8
            otype: NUMBER
        ASY_Code_der_Währungseinheit_des_Kindes:
            type: string
            length: 3
            otype: CHAR
