SkyFlow\GermanyCustomsBundle\Entity\N22500:
    type: entity
    table: gc_N22500
    description: 'AWR- Ausnahmeregelungen für bestimmte geographische Gebiete'
    fields:
        AVM_Endedatum:
            type: edidatetime
            otype: DATE
    id:
        AVJ_SID:
            type: integer
            length: 8
            otype: NUMBER
        AVK_Schlüssel_eines_Landes_oder_einer_Ländergruppe:
            type: string
            length: 4
            otype: CHAR
        AVL_Beginndatum:
            type: edidatetime
            otype: DATE
