SkyFlow\GermanyCustomsBundle\Entity\N22505:
    type: entity
    table: gc_N22505
    description: Verfahrensbeschr채nkungen
    fields:
        AVP_Endedatum:
            type: edidatetime
            otype: DATE
        AVQ_Beschreibung_der_Verfahrensbeschr채nkung:
            type: text
            length: 2000
            otype: LONG
    id:
        AVN_Schl체ssel_der_Verfahrensbeschr채nkung:
            type: string
            length: 3
            otype: CHAR
        AVO_Beginndatum:
            type: edidatetime
            otype: DATE
