SkyFlow\GermanyCustomsBundle\Entity\N23000:
    type: entity
    table: gc_N23000
    description: 'zu verwendende Verbuchungsstellen'
    fields:
        AVS_Buchungsschlüssel_EU_Code:
            type: string
            length: 5
            otype: VARCHAR
        AVU_Endedatum:
            type: edidatetime
            otype: DATE
        AVV_nationale_Verbuchungsstelle_der_Einnahmen:
            type: string
            length: 200
            otype: VARCHAR
        AVW_Zusatzinformationen_zur_Verbuchungsstelle:
            type: string
            length: 200
            otype: VARCHAR
        AVX_Beschreibung_der_Abgaben:
            type: string
            length: 2000
            otype: LONG
    id:
        AVR_Buchungsschlüssel:
            type: string
            length: 5
            otype: CHAR
        AVT_Beginndatum:
            type: edidatetime
            otype: DATE
