SkyFlow\GermanyCustomsBundle\Entity\N25005:
    type: entity
    table: gc_N25005
    description: 'Währungseinheitscode der Umrechnungskurse'
    fields:
        AWR_Endedatum:
            type: edidatetime
            otype: DATE
        AWS_ECU_Umrechnungskurs:
            type: decimal
            precision: 6
            scale: 5
            otype: NUMBER
        AWT_Beschreibung_des_ECU__Umrechnungskurses:
            type: string
            length: 200
            otype: VARCHAR
    id:
        AWP_Schlüssel_des_ECU__Währungseinheitscodes:
            type: string
            length: 3
            otype: CHAR
        AWQ_Beginndatum:
            type: edidatetime
            otype: DATE
