SkyFlow\GermanyCustomsBundle\Entity\N50400:
    type: entity
    table: gc_N50400
    description: 'Zuordnung Ausfuhrerstattungsnomenklatur – Hinweise'
    fields:
        BHH_Endedatum:
            type: edidatetime
            otype: DATE
    id:
        BHF_SID_der_nationalen_AE_Nomenklatur:
            type: integer
            length: 8
            otype: NUMBER
        BHG_Beginndatum:
            type: edidatetime
            otype: DATE
        BHI_Hinweisart:
            type: string
            length: 3
            otype: CHAR
        BHJ_Hinweis:
            type: string
            length: 4
            otype: VARCHAR
