SkyFlow\GermanyCustomsBundle\Entity\T20500:
    type: entity
    table: gc_T20500
    description: Bescheinigung
    fields:
        ACC_Datum_des_Gültigkeitsbeginns_der_Bescheinigung:
            type: edidatetime
            otype: DATE
        ACD_Gültigkeitsendedatum_der_Bescheinigung:
            type: edidatetime
            otype: DATE
    id:
        ACA_Bescheinigungsartcode:
            type: string
            length: 1
            otype: CHAR
        ACB_Bescheinigungskontrollnummer:
            type: string
            length: 3
            otype: CHAR
