SkyFlow\GermanyCustomsBundle\Entity\T20505:
    type: entity
    table: gc_T20505
    description: 'Bescheinigungsbeschreibung Zeitraum'
    fields:
        ACF_Bescheinigungsartcode:
            type: string
            length: 1
            otype: CHAR
        ACG_Bescheinigungskontrollnummer:
            type: string
            length: 3
            otype: CHAR
        ACH_Datum_des_Gültigkeitsbeginn_der_Bescheinigung:
            type: edidatetime
            otype: DATE
        ACI_Datum_des_Gültigkeitsende_der_Bescheinigung:
            type: edidatetime
            otype: DATE
        ACJ_Beschreibung_der_Bescheinigung:
            type: string
            length: 500
            otype: VARCHAR
    id:
        ACE_SID_der_Bescheinigungsbeschreibung:
            type: integer
            length: 8
            otype: NUMBER
