SkyFlow\GermanyCustomsBundle\Entity\T22000:
    type: entity
    table: gc_T22000
    description: 'Erlaubte KombinationenMaßeinheit/ Qualifikator'
    fields:
        ACU_Beginndatum:
            type: edidatetime
            otype: DATE
        ACV_Endedatum:
            type: edidatetime
            otype: DATE
    id:
        ACS_Maßeinheitscode:
            type: string
            length: 3
            otype: CHAR
        ACT_Code_des_Maßeinheitsqualifikators:
            type: string
            length: 1
            otype: CHAR
