SkyFlow\GermanyCustomsBundle\Entity\T24515:
    type: entity
    table: gc_T24515
    description: 'Verbindung des Zusatzcodes mit Fußnoten'
    fields:
        AEM_Gültigkeitsendedatum_der_Verbindung_zwischen_Zusatzcodes_un:
            type: edidatetime
            otype: DATE
        AEN_Zusatzcodeart_ID:
            type: string
            length: 1
            otype: CHAR
        AEO_Zusatzcode:
            type: string
            length: 3
            otype: CHAR
    id:
        AEI_SID_des_Zusatzcodes:
            type: integer
            length: 8
            otype: NUMBER
        AEJ_Fußnotenart_ID:
            type: string
            length: 3
            otype: CHAR
        AEK_Fußnoten_ID:
            type: string
            length: 5
            otype: CHAR
        AEL_Datum_des_Gültigkeitsbeginns_der_Verbindung_zwischen_Zusatz:
            type: edidatetime
            otype: DATE
