SkyFlow\GermanyCustomsBundle\Entity\T32000:
    type: entity
    table: gc_T32000
    description: Meursing-Tabellenplan
    fields:
        AJC_Datum_des_Gültigkeitsbeginns_des_Meursing_Tabellenplans:
            type: edidatetime
            otype: DATE
        AJD_Gültigkeitsendedatum_des_Meursing__Tabellenplans:
            type: edidatetime
            otype: DATE
    id:
        AJB_ID_des_Meursing_Tabellenplans:
            type: string
            length: 2
            otype: CHAR
