SkyFlow\GermanyCustomsBundle\Entity\T34005:
    type: entity
    table: gc_T34005
    description: 'Zellenkomponente der Meursing-Tabelle'
    fields:
        AKI_Gültigkeitsendedatum_der_Zellenkomponente_der_Meursing_Tabe:
            type: edidatetime
            otype: DATE
        AKJ_Zusatzcode_Meursing:
            type: string
            length: 3
            otype: CHAR
    id:
        AKC_SID_für_Zusatzcode_Meursing:
            type: integer
            length: 8
            otype: NUMBER
        AKD_ID_des_Meursing_Tabellenplans:
            type: string
            length: 2
            otype: CHAR
        AKE_Meursing_Positionsnummer:
            type: string
            length: 3
            otype: CHAR
        AKF_Meursing_Reihen__Spaltencode:
            type: string
            length: 1
            otype: CHAR
        AKG_Sequentielle_Nummer_der_Meursing_Unterposition:
            type: string
            length: 4
            otype: CHAR
        AKH_Datum_des_Gültigkeitsbeginns_der_Zellenkomponente_der_Meurs:
            type: edidatetime
            otype: DATE
