SkyFlow\GermanyCustomsBundle\Entity\T36015:
    type: entity
    table: gc_T36015
    description: 'Ausschlüsse Ursprungsland Ordnungsnummer QUOTA'
    fields: {  }
    id:
        ALC_SID_Ursprungsland_Ordnungsnummer:
            type: integer
            length: 8
            otype: NUMBER
        ALD_Ausgeschlossenes_geographisches_Gebiet:
            type: integer
            length: 8
            otype: NUMBER
