SkyFlow\GermanyCustomsBundle\Entity\T36010:
    type: entity
    table: gc_T36010
    description: 'Ursprungsland Ordnungsnummer QUOTA'
    fields:
        AKX_SID_der_Ordnungsnummer:
            type: integer
            length: 8
            otype: NUMBER
        AKY_Geographisches_Gebiet:
            type: string
            length: 4
            otype: CHAR
        AKZ_Gültigkeitsbeginn:
            type: edidatetime
            otype: DATE
        ALA_Gültigkeitsende:
            type: edidatetime
            otype: DATE
        ALB_SID_des_geographischen_Gebiets:
            type: integer
            length: 8
            otype: NUMBER
    id:
        AKW_SID:
            type: integer
            length: 8
            otype: NUMBER
