SkyFlow\GermanyCustomsBundle\Entity\T37000:
    type: entity
    table: gc_T37000
    description: 'Beschreibung QUOTA'
    fields:
        ALF_Ordnungsnummer:
            type: string
            length: 6
            otype: CHAR
        ALG_Gültigkeitsbeginn:
            type: edidatetime
            otype: DATE
        ALH_SID_der_Ordnungsnummer:
            type: integer
            length: 8
            otype: NUMBER
        ALI_Gültigkeitsende:
            type: edidatetime
            otype: DATE
        ALJ_Kontingentsmenge:
            type: decimal
            precision: 14
            scale: 3
            otype: NUMBER
        ALK_Ausgangsmenge:
            type: decimal
            precision: 14
            scale: 3
            otype: NUMBER
        ALL_Währungseinheitscode:
            type: string
            length: 3
            otype: CHAR
        ALM_Maßeinheitscode:
            type: string
            length: 3
            otype: CHAR
        ALN_Maßeinheitsqualifikator:
            type: string
            length: 1
            otype: CHAR
        ALO_Kennzeichen_maximale_Austarifierung:
            type: integer
            length: 1
            otype: NUMBER
        ALP_kritischer_Status:
            type: string
            length: 1
            otype: CHAR
        ALQ_kritischer_Schwellenwert:
            type: integer
            length: 3
            otype: NUMBER
        ALR_Kurzbeschreibung:
            type: string
            length: 500
            otype: VARCHAR
    id:
        ALE_SID_der_QUOTA_Beschreibung:
            type: integer
            length: 8
            otype: NUMBER
