SkyFlow\GermanyCustomsBundle\Entity\T40010:
    type: entity
    table: gc_T40010
    description: Warennomenklaturbeschreibung
    fields:
        ANZ_SID_der_Warennomenklatur:
            type: integer
            length: 8
            otype: NUMBER
        AOA_Datum_des_Gültigkeitsbeginns_der_Warennomenklaturbeschreibu:
            type: edidatetime
            otype: DATE
        AOB_Gültigkeitsendedatum_der_Warennomenklaturbeschreibung:
            type: edidatetime
            otype: DATE
        AOC_Warennomenklatur_ID:
            type: string
            length: 10
            otype: CHAR
        AOD_Warenliniensuffix:
            type: string
            length: 2
            otype: CHAR
        AOE_Langtext_der_Warennomenklatur:
            type: text
            otype: LONG
    id:
        ANY_SID_der_Warennomenklaturbeschreibung:
            type: integer
            length: 8
            otype: NUMBER
