SkyFlow\GermanyCustomsBundle\Entity\T40035:
    type: entity
    table: gc_T40035
    description: Warennomenklaturursprung
    fields:
        AOW_Warennomenklatur_ID:
            type: string
            length: 10
            otype: CHAR
        AOX_Warenliniensuffix:
            type: string
            length: 2
            otype: CHAR
    id:
        AOT_SID_der_Warennomenklatur:
            type: integer
            length: 8
            otype: NUMBER
        AOU_stammt_aus_Warennomenklatur:
            type: string
            length: 10
            otype: CHAR
        AOV_stammt_aus_Warenliniensuffix:
            type: string
            length: 2
            otype: CHAR
