SkyFlow\GermanyCustomsBundle\Entity\T41020:
    type: entity
    table: gc_T41020
    description: 'Zuordnung Ausfuhrerstattungsnomenklaturcode – Fußnote'
    fields:
        AQH_Gültigkeitsendedatum_der_Verbindung_zwischen_der_Ausfuhrers:
            type: edidatetime
            otype: DATE
        AQI_Warennomenklatur_ID:
            type: string
            length: 10
            otype: CHAR
        AQJ_Zusatzcodeart:
            type: string
            length: 1
            otype: CHAR
        AQK_Ausfuhrerstattungscode:
            type: string
            length: 3
            otype: CHAR
        AQL_Warenliniensuffix:
            type: string
            length: 2
            otype: CHAR
    id:
        AQD_SID_für_die_Ausfuhrerstattungsnomenklatur:
            type: integer
            length: 8
            otype: NUMBER
        AQE_Fußnotenart_ID:
            type: string
            length: 3
            otype: CHAR
        AQF_Fußnoten_ID:
            type: string
            length: 5
            otype: CHAR
        AQG_Datum_des_Gültigkeitsbeginns_der_Verbindung_zwischen_der_Au:
            type: edidatetime
            otype: DATE
