SkyFlow\GermanyCustomsBundle\Entity\T43000:
    type: entity
    table: gc_T43000
    description: Maßnahmen
    fields:
        AQN_Maßnahmeart:
            type: string
            length: 6
            otype: CHAR
        AQO_ID_des_geographischen_Gebiets:
            type: string
            length: 4
            otype: CHAR
        AQP_Warennomenklatur_ID:
            type: string
            length: 10
            otype: CHAR
        AQQ_Zusatzcodeart:
            type: string
            length: 1
            otype: CHAR
        AQR_Zusatzcode:
            type: string
            length: 3
            otype: CHAR
        AQS_Ordnungsnummer:
            type: string
            length: 6
            otype: CHAR
        AQT_Reduktionsindikator:
            type: string
            length: 1
            otype: CHAR
        AQU_Datum_des_Gültigkeitsbeginns_der_Maßnahme:
            type: edidatetime
            otype: DATE
        AQV_Funktionsart_der_maßnahmegenerierenden_Verordnung:
            type: string
            length: 1
            otype: CHAR
        AQW_ID_der_maßnahmegenerierenden_Verordnung:
            type: string
            length: 8
            otype: CHAR
        AQX_Gültigkeitsendedatum_der_Maßnahme:
            type: edidatetime
            otype: DATE
        AQY_Funktion_der_Begründungsverordnung:
            type: string
            length: 1
            otype: CHAR
        AQZ_ID_der_Begründungsverordnung:
            type: string
            length: 8
            otype: CHAR
        ARA_Ausgesetztes_Merkmal:
            type: string
            length: 1
            otype: CHAR
        ARB_SID_des_geographischen_Gebiets:
            type: integer
            length: 8
            otype: NUMBER
        ARC_SID_der_Warennomenklatur:
            type: integer
            length: 8
            otype: NUMBER
        ARD_SID_des_Zusatzcodes:
            type: integer
            length: 8
            otype: NUMBER
        ARE_SID_der_Ausfuhrerstattungsnomenklatur:
            type: integer
            length: 8
            otype: NUMBER
        ARF_Ausgesetztes_Merkmal_der_maßnahmegenerierenden_Verordnung:
            type: string
            length: 1
            otype: CHAR
        ARG_Regime_ID_der_maßnahmegenerierenden_Verordnung:
            type: string
            length: 3
            otype: CHAR
    id:
        AQM_SID_der_Maßnahme:
            type: integer
            length: 8
            otype: NUMBER
