SkyFlow\GermanyCustomsBundle\Entity\T43020:
    type: entity
    table: gc_T43020
    description: 'Verbindung Maßnahme – Fußnoten'
    fields: {  }
    id:
        ASH_SID_der_Maßnahme:
            type: integer
            length: 8
            otype: NUMBER
        ASI_Fußnotenart_ID:
            type: string
            length: 3
            otype: CHAR
        ASJ_Fußnote_ID:
            type: string
            length: 5
            otype: CHAR
